### ISSUE TITLE
Python extension

### ISSUE THREAD

**Issue by heshamfm** [staruml/staruml-dev-docs#1]
Hi,

Thanks for the great work.

Any plan for Python extension? If not, how can we contribute python? docs?

Thanks

**Comment by staruml** [comment]
Hi,

Currently we don't have plan to develop Python extension. If you are interested in developing Python extension, we strongly encourage you. Please see the dev docs: https://github.com/staruml/staruml-dev-docs/wiki

Thanks

**Comment by niklauslee** [comment]
I've started to develop Python extension (https://github.com/niklauslee/staruml-python). Any contributions are welcome.
